name: "Build vapoursynth"

on:
  workflow_dispatch:

env:
  ARCHIVE_NAME: vapoursynth-build-linux-x86_64-2404.tar.gz

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: automake autoconf libtool libtool-bin build-essential nasm python3 python3-pip python3-dev cython3
          version: 1.0

      - name: Build vapoursynth
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd ${{ github.workspace }}
          python3 -m pip install --upgrade pip
          pip3 install --break-system-packages --upgrade cython
          mkdir workspace
          wget -O zimg-release-3.0.6.tar.gz https://github.com/sekrit-twc/zimg/archive/refs/tags/release-3.0.6.tar.gz
          tar xzf zimg-release-3.0.6.tar.gz
          cd zimg-release-3.0.6
          ./autogen.sh
          ./configure --prefix="${{ github.workspace }}/workspace"
          make
          make install
          export PKG_CONFIG_PATH="${{ github.workspace }}/workspace/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH="${{ github.workspace }}/workspace/lib:$LD_LIBRARY_PATH"
          cd ${{ github.workspace }}
          wget -O vapoursynth-R73.tar.gz https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R73.tar.gz
          tar xzf vapoursynth-R73.tar.gz
          cd vapoursynth-R73
          ./autogen.sh
          ./configure --prefix="${{ github.workspace }}/workspace"
          make
          make install

      - name: Create binary archive
        run: >-
          tar -cvzf ${{ env.ARCHIVE_NAME }}
          --owner=root --group=root
          -C ${{ github.workspace }}
          workspace

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: vapoursynth-linux-glibc-x86_64-2404
          path: ${{ env.ARCHIVE_NAME }}
          if-no-files-found: error

  github-release:
    name: Create GitHub release
    runs-on: ubuntu-24.04

    needs:
      - build-linux

    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          'vapoursynth2404-${{ github.sha }}'
          --repo '${{ github.repository }}'
          --title 'vapoursynth build'
          --notes "vapoursynth build including zimg for compiling plugins (not intended for general use)"
          --latest=false 

      - name: Upload artifacts to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}

        run: |
          gh release upload \
          'vapoursynth2404-${{ github.sha }}' \
          'vapoursynth-linux-glibc-x86_64-2404/${{ env.ARCHIVE_NAME }}' \
          --repo '${{ github.repository }}'

